#!/bin/bash
# Zawra Unified CLI

# Resolve the absolute path of this script, even if it's a symlink
SCRIPT_DIR="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" &> /dev/null && pwd )"
CMD_PATH="${SCRIPT_DIR}/tools/crawler/query.py"

if [ "$1" == "update" ]; then
    "${SCRIPT_DIR}/tools/crawler/inventory_crawler.py"
else
    "$CMD_PATH" "$@"
fi

