partial interface DedicatedWorkerGlobalScope {
    [EnabledBySetting=CompressionStreamEnabled] attribute CompressionStreamConstructor CompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute CompressionStreamEncoderConstructor CompressionStreamEncoder;
    [EnabledBySetting=CompressionStreamEnabled] attribute DecompressionStreamConstructor DecompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute DecompressionStreamDecoderConstructor DecompressionStreamDecoder;
    [EnabledBySetting=AccessHandleEnabled, SecureContext] attribute FileSystemSyncAccessHandleConstructor FileSystemSyncAccessHandle;
    [EnabledBySetting=MediaCapabilitiesEnabled] attribute MediaCapabilitiesConstructor MediaCapabilities;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCEncodedAudioFrameConstructor RTCEncodedAudioFrame;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCEncodedVideoFrameConstructor RTCEncodedVideoFrame;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCSFrameTransformEnabled] attribute RTCRtpSFrameTransformConstructor SFrameTransform;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCSFrameTransformEnabled] attribute RTCRtpSFrameTransformErrorEventConstructor SFrameTransformErrorEvent;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCRtpScriptTransformerConstructor RTCRtpScriptTransformer;
    [Conditional=NOTIFICATIONS, EnabledBySetting=NotificationsEnabled] attribute NotificationConstructor Notification;
    [EnabledBySetting=PermissionsAPIEnabled] attribute PermissionStatusConstructor PermissionStatus;
    attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamConstructor TransformStream;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamDefaultControllerConstructor TransformStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamConstructor WritableStream;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultControllerConstructor WritableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultWriterConstructor WritableStreamDefaultWriter;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsEnabled] attribute WebCodecsEncodedVideoChunkConstructor EncodedVideoChunk;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsEnabled] attribute WebCodecsVideoDecoderConstructor VideoDecoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsEnabled] attribute WebCodecsVideoEncoderConstructor VideoEncoder;
    [Conditional=WEB_CODECS, EnabledBySetting=WebCodecsEnabled] attribute WebCodecsVideoFrameConstructor VideoFrame;
    attribute AbortControllerConstructor AbortController;
    [PrivateIdentifier, PublicIdentifier] attribute AbortSignalConstructor AbortSignal;
    attribute CustomEventConstructor CustomEvent;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    attribute TextDecoderConstructor TextDecoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextDecoderStreamConstructor TextDecoderStream;
    attribute TextEncoderConstructor TextEncoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextEncoderStreamConstructor TextEncoderStream;
    [EnabledBySetting=FileReaderAPIEnabled] attribute FileReaderSyncConstructor FileReaderSync;
    attribute DOMURLConstructor URL;
    attribute URLSearchParamsConstructor URLSearchParams;
    attribute PerformanceConstructor Performance;
    attribute PerformanceEntryConstructor PerformanceEntry;
    attribute PerformanceMarkConstructor PerformanceMark;
    attribute PerformanceMeasureConstructor PerformanceMeasure;
    attribute PerformanceObserverConstructor PerformanceObserver;
    attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    [EnabledByDeprecatedGlobalSetting=ServerTimingEnabled] attribute PerformanceServerTimingConstructor PerformanceServerTiming;
    attribute DedicatedWorkerGlobalScopeConstructor DedicatedWorkerGlobalScope;
    attribute WorkerConstructor Worker;
    attribute XMLHttpRequestConstructor XMLHttpRequest;
};
