/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"
#include "JSGPUPipelineErrorReason.h"

#include <JavaScriptCore/JSCInlines.h>
#include <JavaScriptCore/JSString.h>
#include <wtf/NeverDestroyed.h>
#include <wtf/SortedArrayMap.h>


namespace WebCore {
using namespace JSC;

String convertEnumerationToString(GPUPipelineErrorReason enumerationValue)
{
    static const NeverDestroyed<String> values[] = {
        MAKE_STATIC_STRING_IMPL("validation"),
        MAKE_STATIC_STRING_IMPL("internal"),
    };
    static_assert(static_cast<size_t>(GPUPipelineErrorReason::Validation) == 0, "GPUPipelineErrorReason::Validation is not 0 as expected");
    static_assert(static_cast<size_t>(GPUPipelineErrorReason::Internal) == 1, "GPUPipelineErrorReason::Internal is not 1 as expected");
    ASSERT(static_cast<size_t>(enumerationValue) < std::size(values));
    return values[static_cast<size_t>(enumerationValue)];
}

template<> JSString* convertEnumerationToJS(VM& vm, GPUPipelineErrorReason enumerationValue)
{
    return jsStringWithCache(vm, convertEnumerationToString(enumerationValue));
}

template<> std::optional<GPUPipelineErrorReason> parseEnumerationFromString<GPUPipelineErrorReason>(const String& stringValue)
{
    static constexpr std::pair<ComparableASCIILiteral, GPUPipelineErrorReason> mappings[] = {
        { "internal", GPUPipelineErrorReason::Internal },
        { "validation", GPUPipelineErrorReason::Validation },
    };
    static constexpr SortedArrayMap enumerationMapping { mappings };
    if (auto* enumerationValue = enumerationMapping.tryGet(stringValue); LIKELY(enumerationValue))
        return *enumerationValue;
    return std::nullopt;
}

template<> std::optional<GPUPipelineErrorReason> parseEnumeration<GPUPipelineErrorReason>(JSGlobalObject& lexicalGlobalObject, JSValue value)
{
    return parseEnumerationFromString<GPUPipelineErrorReason>(value.toWTFString(&lexicalGlobalObject));
}

template<> const char* expectedEnumerationValues<GPUPipelineErrorReason>()
{
    return "\"validation\", \"internal\"";
}

} // namespace WebCore
