partial interface PaintWorkletGlobalScope {
    [EnabledBySetting=CompressionStreamEnabled] attribute CompressionStreamConstructor CompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute CompressionStreamEncoderConstructor CompressionStreamEncoder;
    [EnabledBySetting=CompressionStreamEnabled] attribute DecompressionStreamConstructor DecompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute DecompressionStreamDecoderConstructor DecompressionStreamDecoder;
    attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamConstructor TransformStream;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamDefaultControllerConstructor TransformStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamConstructor WritableStream;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultControllerConstructor WritableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultWriterConstructor WritableStreamDefaultWriter;
    [Conditional=CSS_PAINTING_API, EnabledBySetting=CSSPaintingAPIEnabled] attribute CSSPaintSizeConstructor CSSPaintSize;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSKeywordValueConstructor CSSKeywordValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSNumericValueConstructor CSSNumericValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSOMVariableReferenceValueConstructor CSSVariableReferenceValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSStyleImageValueConstructor CSSImageValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSStyleValueConstructor CSSStyleValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSUnitValueConstructor CSSUnitValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSUnparsedValueConstructor CSSUnparsedValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute StylePropertyMapReadOnlyConstructor StylePropertyMapReadOnly;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSColorConstructor CSSColor;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSColorValueConstructor CSSColorValue;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSHSLConstructor CSSHSL;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSHWBConstructor CSSHWB;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSLCHConstructor CSSLCH;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSLabConstructor CSSLab;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSOKLCHConstructor CSSOKLCH;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSOKLabConstructor CSSOKLab;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSRGBConstructor CSSRGB;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathClampConstructor CSSMathClamp;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathInvertConstructor CSSMathInvert;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathMaxConstructor CSSMathMax;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathMinConstructor CSSMathMin;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathNegateConstructor CSSMathNegate;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathProductConstructor CSSMathProduct;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathSumConstructor CSSMathSum;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathValueConstructor CSSMathValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSNumericArrayConstructor CSSNumericArray;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMatrixComponentConstructor CSSMatrixComponent;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSPerspectiveConstructor CSSPerspective;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSRotateConstructor CSSRotate;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSScaleConstructor CSSScale;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewConstructor CSSSkew;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewXConstructor CSSSkewX;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewYConstructor CSSSkewY;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTransformComponentConstructor CSSTransformComponent;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTransformValueConstructor CSSTransformValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTranslateConstructor CSSTranslate;
    attribute AbortControllerConstructor AbortController;
    [PrivateIdentifier, PublicIdentifier] attribute AbortSignalConstructor AbortSignal;
    attribute CustomEventConstructor CustomEvent;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    attribute TextDecoderConstructor TextDecoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextDecoderStreamConstructor TextDecoderStream;
    attribute TextEncoderConstructor TextEncoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextEncoderStreamConstructor TextEncoderStream;
    attribute DOMURLConstructor URL;
    attribute URLSearchParamsConstructor URLSearchParams;
    [Conditional=CSS_PAINTING_API, EnabledBySetting=CSSPaintingAPIEnabled] attribute PaintRenderingContext2DConstructor PaintRenderingContext2D;
    attribute PerformanceConstructor Performance;
    attribute PerformanceEntryConstructor PerformanceEntry;
    attribute PerformanceMarkConstructor PerformanceMark;
    attribute PerformanceMeasureConstructor PerformanceMeasure;
    attribute PerformanceObserverConstructor PerformanceObserver;
    attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    [EnabledByDeprecatedGlobalSetting=ServerTimingEnabled] attribute PerformanceServerTimingConstructor PerformanceServerTiming;
    [Conditional=CSS_PAINTING_API, EnabledBySetting=CSSPaintingAPIEnabled] attribute PaintWorkletGlobalScopeConstructor PaintWorkletGlobalScope;
};
