partial interface ServiceWorkerGlobalScope {
    [EnabledBySetting=CompressionStreamEnabled] attribute CompressionStreamConstructor CompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute CompressionStreamEncoderConstructor CompressionStreamEncoder;
    [EnabledBySetting=CompressionStreamEnabled] attribute DecompressionStreamConstructor DecompressionStream;
    [EnabledBySetting=CompressionStreamEnabled, PrivateIdentifier] attribute DecompressionStreamDecoderConstructor DecompressionStreamDecoder;
    [Conditional=NOTIFICATIONS, EnabledBySetting=NotificationsEnabled] attribute NotificationConstructor Notification;
    [Conditional=NOTIFICATION_EVENT, EnabledBySetting=NotificationEventEnabled] attribute NotificationEventConstructor NotificationEvent;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushEventConstructor PushEvent;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled] attribute PushMessageDataConstructor PushMessageData;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushSubscriptionChangeEventConstructor PushSubscriptionChangeEvent;
    attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamConstructor TransformStream;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamDefaultControllerConstructor TransformStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamConstructor WritableStream;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultControllerConstructor WritableStreamDefaultController;
    [PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultWriterConstructor WritableStreamDefaultWriter;
    attribute AbortControllerConstructor AbortController;
    [PrivateIdentifier, PublicIdentifier] attribute AbortSignalConstructor AbortSignal;
    attribute CustomEventConstructor CustomEvent;
    attribute ErrorEventConstructor ErrorEvent;
    attribute EventConstructor Event;
    attribute EventTargetConstructor EventTarget;
    attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    attribute TextDecoderConstructor TextDecoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextDecoderStreamConstructor TextDecoderStream;
    attribute TextEncoderConstructor TextEncoder;
    [EnabledBySetting=TransformStreamAPIEnabled] attribute TextEncoderStreamConstructor TextEncoderStream;
    attribute DOMURLConstructor URL;
    attribute URLSearchParamsConstructor URLSearchParams;
    attribute PerformanceConstructor Performance;
    attribute PerformanceEntryConstructor PerformanceEntry;
    attribute PerformanceMarkConstructor PerformanceMark;
    attribute PerformanceMeasureConstructor PerformanceMeasure;
    attribute PerformanceObserverConstructor PerformanceObserver;
    attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    [EnabledByDeprecatedGlobalSetting=ServerTimingEnabled] attribute PerformanceServerTimingConstructor PerformanceServerTiming;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ExtendableEventConstructor ExtendableEvent;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ExtendableMessageEventConstructor ExtendableMessageEvent;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute FetchEventConstructor FetchEvent;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ServiceWorkerClientConstructor Client;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ServiceWorkerClientsConstructor Clients;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ServiceWorkerGlobalScopeConstructor ServiceWorkerGlobalScope;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled] attribute ServiceWorkerWindowClientConstructor WindowClient;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchEventConstructor BackgroundFetchEvent;
};
