partial interface ShadowRealmGlobalScope {
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&CompressionStreamEnabled] attribute CompressionStreamConstructor CompressionStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&CompressionStreamEnabled, PrivateIdentifier] attribute CompressionStreamEncoderConstructor CompressionStreamEncoder;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&CompressionStreamEnabled] attribute DecompressionStreamConstructor DecompressionStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&CompressionStreamEnabled, PrivateIdentifier] attribute DecompressionStreamDecoderConstructor DecompressionStreamDecoder;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute ByteLengthQueuingStrategyConstructor ByteLengthQueuingStrategy;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute CountQueuingStrategyConstructor CountQueuingStrategy;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier] attribute ReadableByteStreamControllerConstructor ReadableByteStreamController;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute ReadableStreamConstructor ReadableStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier] attribute ReadableStreamBYOBReaderConstructor ReadableStreamBYOBReader;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier] attribute ReadableStreamBYOBRequestConstructor ReadableStreamBYOBRequest;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultControllerConstructor ReadableStreamDefaultController;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute ReadableStreamDefaultReaderConstructor ReadableStreamDefaultReader;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamConstructor TransformStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&TransformStreamAPIEnabled, PrivateIdentifier, PublicIdentifier] attribute TransformStreamDefaultControllerConstructor TransformStreamDefaultController;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute WritableStreamConstructor WritableStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultControllerConstructor WritableStreamDefaultController;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute WritableStreamDefaultWriterConstructor WritableStreamDefaultWriter;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute AbortControllerConstructor AbortController;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled, PrivateIdentifier, PublicIdentifier] attribute AbortSignalConstructor AbortSignal;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute CustomEventConstructor CustomEvent;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute ErrorEventConstructor ErrorEvent;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute EventConstructor Event;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute EventTargetConstructor EventTarget;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PromiseRejectionEventConstructor PromiseRejectionEvent;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute TextDecoderConstructor TextDecoder;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&TransformStreamAPIEnabled] attribute TextDecoderStreamConstructor TextDecoderStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute TextEncoderConstructor TextEncoder;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled&TransformStreamAPIEnabled] attribute TextEncoderStreamConstructor TextEncoderStream;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute DOMURLConstructor URL;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute URLSearchParamsConstructor URLSearchParams;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceConstructor Performance;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceEntryConstructor PerformanceEntry;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceMarkConstructor PerformanceMark;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceMeasureConstructor PerformanceMeasure;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceObserverConstructor PerformanceObserver;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceObserverEntryListConstructor PerformanceObserverEntryList;
    [EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceResourceTimingConstructor PerformanceResourceTiming;
    [EnabledByDeprecatedGlobalSetting=ServerTimingEnabled, EnabledBySetting=WebAPIsInShadowRealmEnabled] attribute PerformanceServerTimingConstructor PerformanceServerTiming;
};
