partial interface WorkerGlobalScope {
    [EnabledBySetting=ShapeDetection, SecureContext] attribute BarcodeDetectorConstructor BarcodeDetector;
    [EnabledBySetting=ShapeDetection, SecureContext] attribute FaceDetectorConstructor FaceDetector;
    [EnabledBySetting=ShapeDetection, SecureContext] attribute TextDetectorConstructor TextDetector;
    [EnabledBySetting=CacheAPIEnabled, SecureContext] attribute DOMCacheConstructor Cache;
    [EnabledBySetting=CacheAPIEnabled, SecureContext] attribute DOMCacheStorageConstructor CacheStorage;
    attribute FetchHeadersConstructor Headers;
    [EnabledBySetting=FetchAPIEnabled] attribute FetchRequestConstructor Request;
    [EnabledBySetting=FetchAPIEnabled] attribute FetchResponseConstructor Response;
    [EnabledBySetting=FileSystemAccessEnabled, SecureContext] attribute FileSystemDirectoryHandleConstructor FileSystemDirectoryHandle;
    [EnabledBySetting=FileSystemAccessEnabled, SecureContext] attribute FileSystemFileHandleConstructor FileSystemFileHandle;
    [EnabledBySetting=FileSystemAccessEnabled, SecureContext] attribute FileSystemHandleConstructor FileSystemHandle;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBCursorConstructor IDBCursor;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBCursorWithValueConstructor IDBCursorWithValue;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBDatabaseConstructor IDBDatabase;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBFactoryConstructor IDBFactory;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBIndexConstructor IDBIndex;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBKeyRangeConstructor IDBKeyRange;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBObjectStoreConstructor IDBObjectStore;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBOpenDBRequestConstructor IDBOpenDBRequest;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBRequestConstructor IDBRequest;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBTransactionConstructor IDBTransaction;
    [EnabledBySetting=IndexedDBAPIEnabled] attribute IDBVersionChangeEventConstructor IDBVersionChangeEvent;
    [Conditional=WEB_RTC, EnabledBySetting=PeerConnectionEnabled] attribute RTCDataChannelConstructor RTCDataChannel;
    [Conditional=WEB_RTC, EnabledBySetting=WebRTCEncodedTransformEnabled] attribute RTCTransformEventConstructor RTCTransformEvent;
    [EnabledBySetting=PermissionsAPIEnabled] attribute PermissionsConstructor Permissions;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushManagerConstructor PushManager;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushSubscriptionConstructor PushSubscription;
    [Conditional=SERVICE_WORKER, EnabledBySetting=PushAPIEnabled, SecureContext] attribute PushSubscriptionOptionsConstructor PushSubscriptionOptions;
    [EnabledBySetting=DeprecationReportingEnabled] attribute DeprecationReportBodyConstructor DeprecationReportBody;
    [EnabledBySetting=ReportingEnabled] attribute ReportConstructor Report;
    [EnabledBySetting=ReportingEnabled] attribute ReportBodyConstructor ReportBody;
    [EnabledBySetting=ReportingEnabled] attribute ReportingObserverConstructor ReportingObserver;
    [EnabledBySetting=StorageAPIEnabled, SecureContext] attribute StorageManagerConstructor StorageManager;
    [EnabledBySetting=WebLocksAPIEnabled, SecureContext] attribute WebLockConstructor Lock;
    [EnabledBySetting=WebLocksAPIEnabled, SecureContext] attribute WebLockManagerConstructor LockManager;
    [Conditional=VIDEO] attribute VideoColorSpaceConstructor VideoColorSpace;
    attribute CloseEventConstructor CloseEvent;
    [EnabledBySetting=WebSocketEnabled] attribute WebSocketConstructor WebSocket;
    [Conditional=WEB_CRYPTO, SecureContext] attribute CryptoKeyConstructor CryptoKey;
    [Conditional=WEB_CRYPTO, SecureContext] attribute SubtleCryptoConstructor SubtleCrypto;
    attribute DOMMatrixConstructor DOMMatrix;
    attribute DOMMatrixReadOnlyConstructor DOMMatrixReadOnly;
    attribute FontFaceConstructor FontFace;
    attribute FontFaceSetConstructor FontFaceSet;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSKeywordValueConstructor CSSKeywordValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSNumericValueConstructor CSSNumericValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSOMVariableReferenceValueConstructor CSSVariableReferenceValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSStyleImageValueConstructor CSSImageValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSStyleValueConstructor CSSStyleValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSUnitValueConstructor CSSUnitValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSUnparsedValueConstructor CSSUnparsedValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute StylePropertyMapReadOnlyConstructor StylePropertyMapReadOnly;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSColorConstructor CSSColor;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSColorValueConstructor CSSColorValue;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSHSLConstructor CSSHSL;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSHWBConstructor CSSHWB;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSLCHConstructor CSSLCH;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSLabConstructor CSSLab;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSOKLCHConstructor CSSOKLCH;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSOKLabConstructor CSSOKLab;
    [EnabledBySetting=CSSTypedOMEnabled&CSSTypedOMColorEnabled] attribute CSSRGBConstructor CSSRGB;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathClampConstructor CSSMathClamp;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathInvertConstructor CSSMathInvert;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathMaxConstructor CSSMathMax;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathMinConstructor CSSMathMin;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathNegateConstructor CSSMathNegate;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathProductConstructor CSSMathProduct;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathSumConstructor CSSMathSum;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMathValueConstructor CSSMathValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSNumericArrayConstructor CSSNumericArray;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSMatrixComponentConstructor CSSMatrixComponent;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSPerspectiveConstructor CSSPerspective;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSRotateConstructor CSSRotate;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSScaleConstructor CSSScale;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewConstructor CSSSkew;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewXConstructor CSSSkewX;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSSkewYConstructor CSSSkewY;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTransformComponentConstructor CSSTransformComponent;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTransformValueConstructor CSSTransformValue;
    [EnabledBySetting=CSSTypedOMEnabled] attribute CSSTranslateConstructor CSSTranslate;
    [EnabledBySetting=BroadcastChannelEnabled] attribute BroadcastChannelConstructor BroadcastChannel;
    attribute DOMExceptionConstructor DOMException;
    attribute DOMPointConstructor DOMPoint;
    attribute DOMPointReadOnlyConstructor DOMPointReadOnly;
    attribute DOMQuadConstructor DOMQuad;
    attribute DOMRectConstructor DOMRect;
    attribute DOMRectReadOnlyConstructor DOMRectReadOnly;
    attribute DOMStringListConstructor DOMStringList;
    [Conditional=CHANNEL_MESSAGING] attribute MessageChannelConstructor MessageChannel;
    attribute MessageEventConstructor MessageEvent;
    attribute MessagePortConstructor MessagePort;
    attribute ProgressEventConstructor ProgressEvent;
    attribute SecurityPolicyViolationEventConstructor SecurityPolicyViolationEvent;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier] attribute TextDecoderStreamDecoderConstructor TextDecoderStreamDecoder;
    [EnabledBySetting=TransformStreamAPIEnabled, PrivateIdentifier] attribute TextEncoderStreamEncoderConstructor TextEncoderStreamEncoder;
    attribute BlobConstructor Blob;
    attribute FileConstructor File;
    attribute FileListConstructor FileList;
    [EnabledBySetting=FileReaderAPIEnabled] attribute FileReaderConstructor FileReader;
    attribute DOMFormDataConstructor FormData;
    attribute ImageBitmapConstructor ImageBitmap;
    attribute ImageDataConstructor ImageData;
    [Conditional=OFFSCREEN_CANVAS&OFFSCREEN_CANVAS_IN_WORKERS, EnabledBySetting=OffscreenCanvasEnabled, EnabledForContext] attribute OffscreenCanvasConstructor OffscreenCanvas;
    attribute TextMetricsConstructor TextMetrics;
    attribute CanvasGradientConstructor CanvasGradient;
    attribute CanvasPatternConstructor CanvasPattern;
    attribute ImageBitmapRenderingContextConstructor ImageBitmapRenderingContext;
    [Conditional=OFFSCREEN_CANVAS&OFFSCREEN_CANVAS_IN_WORKERS, EnabledBySetting=OffscreenCanvasEnabled, EnabledForContext] attribute OffscreenCanvasRenderingContext2DConstructor OffscreenCanvasRenderingContext2D;
    attribute Path2DConstructor Path2D;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGL2RenderingContextConstructor WebGL2RenderingContext;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLActiveInfoConstructor WebGLActiveInfo;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLBufferConstructor WebGLBuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLContextEventConstructor WebGLContextEvent;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLFramebufferConstructor WebGLFramebuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLProgramConstructor WebGLProgram;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLQueryConstructor WebGLQuery;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLRenderbufferConstructor WebGLRenderbuffer;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLRenderingContextConstructor WebGLRenderingContext;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLSamplerConstructor WebGLSampler;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLShaderConstructor WebGLShader;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLShaderPrecisionFormatConstructor WebGLShaderPrecisionFormat;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLSyncConstructor WebGLSync;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLTextureConstructor WebGLTexture;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLTransformFeedbackConstructor WebGLTransformFeedback;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLUniformLocationConstructor WebGLUniformLocation;
    [Conditional=WEBGL, EnabledBySetting=WebGLEnabled] attribute WebGLVertexArrayObjectConstructor WebGLVertexArrayObject;
    [Conditional=VIDEO] attribute AudioTrackConfigurationConstructor AudioTrackConfiguration;
    [Conditional=VIDEO] attribute VideoTrackConfigurationConstructor VideoTrackConfiguration;
    attribute CryptoConstructor Crypto;
    attribute EventSourceConstructor EventSource;
    attribute WorkerNavigatorConstructor WorkerNavigator;
    attribute WorkerGlobalScopeConstructor WorkerGlobalScope;
    attribute WorkerLocationConstructor WorkerLocation;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkerNavigationPreloadEnabled] attribute NavigationPreloadManagerConstructor NavigationPreloadManager;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerConstructor ServiceWorker;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerContainerConstructor ServiceWorkerContainer;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled, SecureContext] attribute ServiceWorkerRegistrationConstructor ServiceWorkerRegistration;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchManagerConstructor BackgroundFetchManager;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchRecordConstructor BackgroundFetchRecord;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchRegistrationConstructor BackgroundFetchRegistration;
    [Conditional=SERVICE_WORKER, EnabledBySetting=ServiceWorkersEnabled&BackgroundFetchAPIEnabled] attribute BackgroundFetchUpdateUIEventConstructor BackgroundFetchUpdateUIEvent;
    attribute XMLHttpRequestEventTargetConstructor XMLHttpRequestEventTarget;
    attribute XMLHttpRequestUploadConstructor XMLHttpRequestUpload;
};
