[package]
name = "zawra-browser-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
zawra-browser = { path = ".." }

[[bin]]
name = "fuzz_http_parser"
path = "fuzz_targets/fuzz_http_parser.rs"
test = false
doc = false

[[bin]]
name = "fuzz_url_normalise"
path = "fuzz_targets/fuzz_url_normalise.rs"
test = false
doc = false
