#include "WebProcess/GPU/ShapeDetection/RemoteFaceDetectorProxy.cpp"
#include "WebProcess/GPU/ShapeDetection/RemoteTextDetectorProxy.cpp"
#include "WebProcess/GPU/graphics/ImageBufferShareableBitmapBackend.cpp"
#include "WebProcess/GPU/graphics/PrepareBackingStoreBuffersData.cpp"
#include "WebProcess/GPU/graphics/RemoteDisplayListRecorderProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteGraphicsContextGLProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteGraphicsContextGLProxyFunctionsGenerated.cpp"
#include "WebProcess/GPU/graphics/RemoteImageBufferProxy.cpp"
