#include "NetworkProcess/storage/BrowserDBStorageArea.cpp"
#include "NetworkProcess/storage/CacheStorageCache.cpp"
#include "NetworkProcess/storage/CacheStorageDiskStore.cpp"
#include "NetworkProcess/storage/CacheStorageManager.cpp"
#include "NetworkProcess/storage/CacheStorageMemoryStore.cpp"
#include "NetworkProcess/storage/CacheStorageRegistry.cpp"
#include "NetworkProcess/storage/FileSystemStorageHandle.cpp"
#include "NetworkProcess/storage/FileSystemStorageHandleRegistry.cpp"
