#include "WebProcess/GPU/graphics/RemoteRenderingBackendProxy.cpp"
#include "WebProcess/GPU/graphics/RemoteResourceCacheProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteAdapterProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteBindGroupLayoutProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteBindGroupProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteBufferProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteCommandBufferProxy.cpp"
#include "WebProcess/GPU/graphics/WebGPU/RemoteCommandEncoderProxy.cpp"
