#include "NetworkProcess/storage/FileSystemStorageManager.cpp"
#include "NetworkProcess/storage/IDBStorageConnectionToClient.cpp"
#include "NetworkProcess/storage/IDBStorageManager.cpp"
#include "NetworkProcess/storage/IDBStorageRegistry.cpp"
#include "NetworkProcess/storage/LocalStorageManager.cpp"
#include "NetworkProcess/storage/MemoryStorageArea.cpp"
#include "NetworkProcess/storage/NetworkQuotaManager.cpp"
#include "NetworkProcess/storage/NetworkStorageManager.cpp"
