#include "NetworkProcess/cache/NetworkCacheStorage.cpp"
#include "NetworkProcess/cache/NetworkCacheSubresourcesEntry.cpp"
#include "NetworkProcess/cache/PrefetchCache.cpp"
#include "NetworkProcess/cache/NetworkCacheDataGLib.cpp"
#include "NetworkProcess/cache/NetworkCacheIOChannelGLib.cpp"
#include "NetworkProcess/glib/DNSCache.cpp"
#include "NetworkProcess/glib/WebKitCachedResolver.cpp"
#include "NetworkProcess/glib/WebKitOverridingResolver.cpp"
