#include "RemoteTextureMessageReceiver.cpp"
#include "RemoteTextureViewMessageReceiver.cpp"
#include "RemoteVideoFrameObjectHeapMessageReceiver.cpp"
#include "RemoteVideoFrameObjectHeapProxyProcessorMessageReceiver.cpp"
#include "RemoteWebLockRegistryMessageReceiver.cpp"
#include "ServiceWorkerDownloadTaskMessageReceiver.cpp"
#include "WebBroadcastChannelRegistryMessageReceiver.cpp"
#include "WebLockRegistryProxyMessageReceiver.cpp"
