#include "JSDeprecatedCSSOMPrimitiveValue.cpp"
#include "JSDeprecatedCSSOMRGBColor.cpp"
#include "JSDeprecatedCSSOMRect.cpp"
#include "JSDeprecatedCSSOMValue.cpp"
#include "JSDeprecatedCSSOMValueList.cpp"
#include "JSDeprecationReportBody.cpp"
#include "JSDetectedBarcode.cpp"
#include "JSDetectedFace.cpp"
