#include "Modules/WebGPU/GPUTexture.cpp"
#include "Modules/WebGPU/GPUTextureView.cpp"
#include "Modules/WebGPU/GPUUncapturedErrorEvent.cpp"
#include "Modules/WebGPU/GPUValidationError.cpp"
#include "Modules/WebGPU/Implementation/WebGPUAdapterImpl.cpp"
#include "Modules/WebGPU/Implementation/WebGPUBindGroupImpl.cpp"
#include "Modules/WebGPU/Implementation/WebGPUBindGroupLayoutImpl.cpp"
#include "Modules/WebGPU/Implementation/WebGPUBufferImpl.cpp"
