#include "dom/PointerEventTypeNames.cpp"
#include "dom/PopStateEvent.cpp"
#include "dom/Position.cpp"
#include "dom/PositionIterator.cpp"
#include "dom/ProcessingInstruction.cpp"
#include "dom/ProgressEvent.cpp"
#include "dom/PromiseRejectionEvent.cpp"
#include "dom/PseudoElement.cpp"
