#include "bindings/js/JSDocumentCustom.cpp"
#include "bindings/js/JSDocumentFragmentCustom.cpp"
#include "bindings/js/JSElementCustom.cpp"
#include "bindings/js/JSElementInternalsCustom.cpp"
#include "bindings/js/JSErrorEventCustom.cpp"
#include "bindings/js/JSErrorHandler.cpp"
#include "bindings/js/JSEventCustom.cpp"
#include "bindings/js/JSEventListener.cpp"
