#include "JSAuthenticatorTransport.cpp"
#include "JSAutomationRate.cpp"
#include "JSAvcEncoderConfig.cpp"
#include "JSBackgroundFetchEvent.cpp"
#include "JSBackgroundFetchEventInit.cpp"
#include "JSBackgroundFetchFailureReason.cpp"
#include "JSBackgroundFetchManager.cpp"
#include "JSBackgroundFetchOptions.cpp"
