#include "bytecode/FullCodeOrigin.cpp"
#include "bytecode/FunctionCodeBlock.cpp"
#include "bytecode/GetByStatus.cpp"
#include "bytecode/GetByVariant.cpp"
#include "bytecode/GetterSetterAccessCase.cpp"
#include "bytecode/ICStatusMap.cpp"
#include "bytecode/ICStatusUtils.cpp"
#include "bytecode/InByStatus.cpp"
