#include "wasm/js/WebAssemblyMemoryPrototype.cpp"
#include "wasm/js/WebAssemblyModuleConstructor.cpp"
#include "wasm/js/WebAssemblyModulePrototype.cpp"
#include "wasm/js/WebAssemblyModuleRecord.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorConstructor.cpp"
#include "wasm/js/WebAssemblyRuntimeErrorPrototype.cpp"
#include "wasm/js/WebAssemblyStructConstructor.cpp"
#include "wasm/js/WebAssemblyStructPrototype.cpp"
