#include "runtime/JSFinalizationRegistry.cpp"
#include "runtime/JSFunction.cpp"
#include "runtime/JSGenerator.cpp"
#include "runtime/JSGeneratorFunction.cpp"
#include "runtime/JSGlobalLexicalEnvironment.cpp"
#include "runtime/JSGlobalObject.cpp"
#include "runtime/JSGlobalObjectDebuggable.cpp"
#include "runtime/JSGlobalObjectFunctions.cpp"
